### ISSUE TITLE
Move example contracts from execution/theories

### ISSUE THREAD

**Issue by annenkov** [AU-COBRA/ConCert#15]
Since we have a growing number of contracts implemented directly in Coq, maybe we should create a subfolder `examples` or something like this at the same level as `theories`? Then the structure will be aligned to how I did it for `embedding` and `extraction`

**Comment by jakobbotsch** [comment]
Seems like a good idea, will do that Monday.

**Comment by jakobbotsch** [comment]
@mikkelmilo this will probably cause some conflicts for you..
