### ISSUE TITLE
Delete _CoqProject/Makefile from the "execution" folder?

### ISSUE THREAD

**Issue by annenkov** [AU-COBRA/ConCert#17]
It seems _CoqProject confuses Proof General, it uses the one in the "execution" folder instead of the main one.

**Comment by jakobbotsch** [comment]
I use it often when testing the execution with other Coq versions. What problems are you running into?

**Comment by annenkov** [comment]
Basically, we have to keep in sync _CoqProject in the root folder with the one in the embedding. Otherwise (I run into this issue in Malthe's development of CL translation), if say, you add another subdir `execution` and add corresponding paths/files to the *main* _CoqProject, Proof General will use _CoqProject inside the `execution` folder and imports of modules from newly added dir will fail. But the whole thing will compile fine through general `make`. I spent a couple of hours trying to figure out what's going on :)

**Comment by jakobbotsch** [comment]
Yes, they need to be kept in sync, but we discussed this back in the day :)
the alternative is to use some sed magic to embed the inner one into the outer one on `make`.

**Comment by annenkov** [comment]
Yes, I remember we discussed, but I thought we decided to have one _CoqProject and one Makefile to build them all :)
Do you think it's worth it to keep the possibility of building `executions` separately? If so, maybe we should allow this for `embedding` as well? In this case we could have separate Makefiles and call them from the root.
Alternatively, we might have _CoqProjectEmbedding and _CoqProjectExecution. In the Makefile we could concat the two (so ProofGeneral could see everything) and generate two makefiles. The main Makefile then will run the two makefiles.

**Comment by jakobbotsch** [comment]
> Do you think it's worth it to keep the possibility of building executions separately?

Yes, I use this extensively when working on the execution part with different versions of Coq than supported by the embedding.

> If so, maybe we should allow this for embedding as well? In this case we could have separate Makefiles and call them from the root.

The embedding depends on execution, so this would be a bit weird.

> Alternatively, we might have _CoqProjectEmbedding and _CoqProjectExecution. In the Makefile we could concat the two (so ProofGeneral could see everything) and generate two makefiles. The main Makefile then will run the two makefiles.

It sounds ok to me but I think it is a lot of complexity in the build process, much more than just keeping two files up to date :)

**Comment by annenkov** [comment]
Ok, I agree this adds complexity. Although, after looking on how MetaCoq build scripts look like, it's not too bad :)

I think embedding should not depend on execution. The dependency comes from examples. I can restructure the examples, so I only use my definitions for the embedding and verify functional correctness. Or maybe create a `contracts` folder where we put all the examples.
But then `contracts` will depend on both again. Damn :)

Ok, let's keep it as it is for now. But we should write somewhere (in readme?) that the files must be in sync, because it might be confusing for newcomers.

**Comment by annenkov** [comment]
I committed in the readme. Closing this for now as wontfix.
