### ISSUE TITLE
Publish Concert extraction (at least to rust) as an opam package

### ISSUE THREAD

**Issue by thewalker77** [AU-COBRA/ConCert#201]
Hello everyone,

As per my understanding Concert project is two main projects:

1- An verified extraction plugins from Coq to Rust Liquidity.
2- Verified block chain applications that use the extraction plugins.

I propose we split the extraction plugin from the block chain applications from the extraction plugins, and aim to stabilize the extraction plugin and get it into coq repository:

The process looks to be relatively simple[1] give that concert already uses opam for building. but the only downside is the extra overhead needed to manage releases (stable API and not breaking compatibility ..etc).

Also that may be a good first step to ship concert extraction with coq platform[2].

[1] https://opam.ocaml.org/doc/Packaging.html#Publishing
[2] https://github.com/coq/platform

**Comment by 4ever2** [comment]
Hi,

ConCert is made up of three layers (projects) a smart contract layer, an embedding layer, and an extraction layer.

We have already been talking about moving some parts of both extraction and embedding layers to separate repositories, and eventually, the plan is to have all parts of ConCert released on opam.

We have already started working on this but we currently don't have an estimate of when it will be finished.

Currently, the plan is to move the general extraction infrastructure to the MetaCoq project and move Rust and Elm extraction to separate repositories. We don't plan on moving extraction code for blockchain-specific languages.

Current tasks:
* Update ConCert to recent versions of Coq and MetaCoq #187 #190 #200
* Move the general extraction pipeline to typed-extraction repository #194
* Merge typed-extraction into MetaCoq (work on this should start soon, will be in MetaCoq v1.2)
* Move Rust extraction to a separate repository (in progress)
* Move Elm extraction to a separate repository (in progress)
* Publish rust and elm extraction on opam (might have to wait for MetaCoq v1.2 release)

**Comment by 4ever2** [comment]
Elm and Rust extraction are now released in the Coq opam repository.
